parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Routing\PageEnhancer:
        tags:
            -  { name: dynamic_router_route_enhancer, priority: 90 }
    App\Routing\ContentRepository:
        arguments: ['@doctrine']

